### PR TITLE
Fix model cache and its resetting

### LINKED ISSUE #415: Imported ontologies are never updated after first read
When `contextsLoader.data.keepUpdated` is true, clear cached ontologies when it or any of its transitive imports have changed

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fixes #415

### CODE REVIEW

File: s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java [hunk 1]
```diff
@@ -138,6 +141,34 @@ public OntModel getOntology(String uri) {
         return ontDocumentManager.getOntology(uri, OntModelSpec.OWL_MEM);
     }
 
+
+    /**
+     * Cache is implemented by OntDocumentManager.getInstance().getFileManager(). Additionally, jena may store models in
+     * OntModelSpec.OWL_MEM.getBaseModelMaker and OntModelSpec.OWL_MEM.getImportModelMaker. Specifically, the
+     * ImportModelMaker stores imports and it is necessary to clear
+     * (TODO - it is necessary if FileManager is not set for caching. Verify that this holds when FileManager is set for caching.
```
[the remark this answers is not in the document]
Comment (kostobog) [reply s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java]: TODO comment removed. The comment was not written correctly and is no longer relevant.
`FileManager` is now always set for caching, i.e. regardless of value of `reloadFiles` parameter.

File: s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java [hunk 2]
```diff
@@ -89,6 +90,8 @@ private OntoDocManager() {
     public static OntologyDocumentManager getInstance() {
         if (sInstance == null) {
             sInstance = new OntoDocManager(OntDocumentManager.getInstance());
+            // TODO - not tested!!!
```
[the remark this answers is not in the document]
Comment (kostobog) [reply s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java]: Comment removed.

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java [hunk 3]
```diff
@@ -4,33 +4,219 @@
...
+
+
+        // check cache updated if reloadFiles is true
+        OntoDocManager.setReloadFiles(true);
+        ontoDocManager.registerDocuments(Arrays.asList(rootDir.toPath()));
+        o1ModelAfterChange = ontoDocManager.getOntology(o1.getURI());
+        o2ImportedAfterChange = o1ModelAfterChange.getImportedModel(o2.getURI());
+
+        assertFalse(o1ModelBeforeChange.hashCode() == o1ModelAfterChange.hashCode());
+        assertFalse(o1ModelBeforeChange.isIsomorphicWith(o1ModelAfterChange));
```
Comment (blcham) [inline s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:98]:
```suggestion
        assertSameModel(o1ModelBeforeChange, o1ModelAfterChange);
```

Comment (blcham) [reply s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:98]: you are repeating those 2 lines multiple times ...  how about implementing it in private method that would be named appropriately

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java [hunk 4]
```diff
@@ -4,33 +4,219 @@
...
+        assertTrue(o1ModelBeforeChange.hashCode() == o1ModelAfterChange.hashCode());
+        assertTrue(o1ModelBeforeChange.isIsomorphicWith(o1ModelAfterChange));
+        // TODO - inference layer of imported ont models are not cached
+//        assertTrue(o2ImportedBeforeChange.hashCode() == o2ImportedAfterChange.hashCode());
+        // base models, i.e. models with no inference, are cached
+        assertTrue(o2ImportedBeforeChange.getBaseModel().hashCode() == o2ImportedAfterChange.getBaseModel().hashCode());
+        assertTrue(o2ImportedBeforeChange.isIsomorphicWith(o2ImportedAfterChange));
+
+
+        // check cache updated if reloadFiles is true
```
Comment (blcham) [inline s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:91]: I believe this is in conflict with test method name `ontModelsNotReloadedWhenKeepUpdatedIsFalse` .. shouldn't we split it into mutliptle methods ?

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java [hunk 5]
```diff
@@ -4,33 +4,219 @@
...
+        write(rootDir, o2, "");
+
+        // When reloadFiles is false this method is called only during initialization
+//        ontoDocManager.registerDocuments(Arrays.asList(rootDir.toPath()));
+
+        OntModel o1ModelAfterChange = ontoDocManager.getOntology(o1.getURI());
+        OntModel o2ImportedAfterChange = o1ModelAfterChange.getImportedModel(o2.getURI());
+
+        // CHECK - o1 model retrieved before and after change is the same when cache not updated. Check is done by o1
+        // model objects hash and by the contents of the models
```
Comment (blcham) [inline s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:81]: there are many comments in this test ... can we clear and unify them ... 

what big CHECK means compared to `check cache updated if reloadFiles is true` ... is this CHECK suppose to be TODO ?

**Review by blcham — CHANGES_REQUESTED** [review]
I am afraid this added functionality will hit us back sooner or later since we use deprecated API ...  thus it is very good that you tested it !

However, tests are very hard to read and contains too many strange comments .. Fastest is probably to ask chatbot to improve it. Some test methods are checking multiple things so mostlikely we should split them.

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java (hunk 3 above)
Comment (kostobog) [reply s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java]: Refactored assert patterns into reusable methods.

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java [hunk 6]
```diff
@@ -1,36 +1,233 @@
...
+     * <ol>
+     * <li> Verify that if an ontology file and its import are changed, cached models of the ontology and its import
+     * are properly updated.
+     * <li> Verify that if an imported ontology file is changed, its cached model is properly updated.
+     * </ol>
+     * </ol>
+     * @throws Exception
+     */
+    @Test
+    public void testOntoDocManager_registerDocuments_CacheAndItsUpdateBasedOnReloadFilesValue() throws Exception {
```
Comment (blcham) [inline s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:69]:
```suggestion
    public void registerDocumentsWithReloadFilesFlagCorreclyUpdatesSourceAndCachedOntologies() throws Exception {
```

Comment (blcham) [reply s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:69]: It seems like you are not obeying conventions ... : 
- 1) remove prefix testOntoDocManager_ ... as test methods should not start with "test" prefix and from class OntoDocManagerTest.java it is clear that we are testing OntoDocManager.java  ...
- 2) consider my suggestion if it makes sense

File: s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java [hunk 7]
```diff
@@ -1,36 +1,233 @@
...
+     * <li> Cached ontology files are UPDATED when changed and OntoDocManager.reloadFiles = TRUE
+     * <ol>
+     * <li> Verify that if import clauses of ontology imported by main ontology, the main ontology and its imports are
+     * reladed.
+     * </ol>
+     * </ol>
+     * @throws Exception
+     */
+    @Test
+    public void testOntoDocManager_registerDocuments_CacheAndItsUpdateBasedOnReloadFilesValue_updatingIntermediateImportedModelsImports() throws Exception {
```
Comment (blcham) [inline s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:158]:
```suggestion
    public void registerDocuments_CacheAndItsUpdateBasedOnReloadFilesValue_updatingIntermediateImportedModelsImports() throws Exception {
```

Comment (blcham) [reply s-pipes-core/src/test/java/cz/cvut/spipes/manager/OntoDocManagerTest.java:158]: see comment above

File: s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java [hunk 8]
```diff
@@ -213,11 +285,24 @@ public static Map<String, Model> getAllFile2Model(Path directoryOrFilePath) {
...
+        }
         return file2Model;
     }
 
     // TODO remove this method !!!
-    private static void addSPINRelevantModel(String fileName, Model model) {
+    private static void addSHACLRelevantModel(String fileName, Model model) {
         String baseURI = JenaUtils.getBaseUri(model);
 
         if (baseURI != null) {
```
[the remark this answers is not in the document]
Comment (kostobog) [reply s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java]: Removed

File: s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java [hunk 9]
```diff
@@ -61,18 +61,21 @@ public class OntoDocManager implements OntologyDocumentManager {
     private static Instant lastTime = Instant.now();
     private static boolean reloadFiles = false;
 
-    // TODO remove !!!!!!! this is workaround for registering SPIN related things.
-    private static Model allLoadedFilesModel = ModelFactory.createDefaultModel();
+    private static Map<String, Model> allChangedFiles = new HashMap<>();
+    private static Set<Path> removedFiles = new HashSet<>();
+    private static Set<Path> managedFiles;
```
[the remark this answers is not in the document]
Comment (kostobog) [reply s-pipes-core/src/main/java/cz/cvut/spipes/manager/OntoDocManager.java:67]: Removed

**Comment by kostobog** [comment]
@blcham 
[Commit](https://github.com/kbss-cvut/s-pipes/pull/417/commits/f09250bc0d0bfe363e0a90401d7b44c17e1f30d1) fixes handing of unchanged renamed files, see also [comment ](https://github.com/kbss-cvut/s-pipes/pull/417#discussion_r2354867424) above. I added ([commit](https://github.com/kbss-cvut/s-pipes/pull/417/commits/0e3d26e1e301f705e988b484154ec152f2b7592a)) a test to verify such file system changes were properly handled. 

Additionally, one of the tests was failing because of `OntDocumentManager` IRI to path mapping was polluted from by other tests. This issue was resolved in [commit](https://github.com/kbss-cvut/s-pipes/pull/417/commits/e3d9a5ff22623af1cf08ddea8b4f928116081115) by resetting the mapping in the `OntDocumentManager.reset` method. 

I also did some minor changes in javadoc. There some unused methods which I think can be deleted but for now added TODO to delete because I am not sure if they are not used somewhere else, e.g. spipes editor.
