### PR TITLE
Fix missing handler exceptions

### LINKED ISSUE #286: Exception when running a module
@blcham 
When running a module which rdfizes csv file I get Exception:
```
java.lang.RuntimeException: No handler for char
	cz.cvut.spipes.modules.handlers.HandlerRegistry.getHandler(HandlerRegistry.java:69)
	cz.cvut.spipes.modules.AnnotatedAbstractModule.loadConfiguration(AnnotatedAbstractModule.java:89)
	cz.cvut.spipes.modules.AbstractModule.execute(AbstractModule.java:73)
	cz.cvut.spipes.engine.ExecutionEngineImpl._executePipeline(ExecutionEngineImpl.java:69)
	cz.cvut.spipes.engine.ExecutionEngineImpl.lambda$_executePipeline$6(ExecutionEngineImpl.java:80)
```

### PR DESCRIPTION
**Pull request by kostobog**
@blcham @palagdan 
Fixes #286 .

Add CharacterHandler and ModeHandler and register them in HandlerRegistry.

The ModeHandler in `s-pipes-modules-tabular` while HandlerRegistry is in `s-pipes-core`. I had to somehow register the ModeHandler. I choose to add ModuleRegistration and call its register method the static constructors of the two module classes.
Maybe there is a better way to do that?

### CODE REVIEW

**Comment by blcham** [comment]
@kostobog thank you for implementing this fix

**Comment by blcham** [comment]
@palagdan please revise this PR and if you can fix it by Tuesday, please fix it, otherwise merge this and make new issue.

This issue comes from:
https://github.com/kbss-cvut/s-pipes/pull/276

The problem is that we have loadManualConfiguration function which seems like it is called correcly:
image

but we cannot have handler for the Mode.

File: s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java [hunk 1]
```diff
@@ -0,0 +1,12 @@
+package cz.cvut.spipes.modules;
+
+import cz.cvut.spipes.modules.handlers.HandlerRegistry;
+import cz.cvut.spipes.modules.handlers.ModeHandler;
+
+public class ModuleRegistration {
```
Comment (blcham) [inline s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java:6]: @palagdan  I do not like this for non-reusable param. We should handle it by extending annotation of `@Parameter`.
image

Comment (blcham) [reply s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java:6]: @palagdan please have a look

File: s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/RDF2CSVModule.java [hunk 2]
```diff
@@ -29,7 +29,7 @@
         "The table is constructed from column and row resources defined in TableSchema and saves it as a new CSV file.\n" +
         "</p>")
 public class RDF2CSVModule extends AnnotatedAbstractModule {
-
+    static {ModuleRegistration.register();}
```
Comment (blcham) [inline s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/RDF2CSVModule.java:32]: don't like it, see above.

File: s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java [hunk 3]
```diff
@@ -97,7 +97,7 @@
  */
 @SPipesModule(label = "Tabular module", comment = "Module for converting tabular data (e.g. CSV or TSV) to RDF")
 public class TabularModule extends AnnotatedAbstractModule {
-
+    static {ModuleRegistration.register();}
```
Comment (blcham) [inline s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java:100]: don't like it, see above.

**Review by blcham — CHANGES_REQUESTED** [review]
@palagdan please have a look at my comments

File: s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java (hunk 1 above)
Comment (palagdan) [reply s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/ModuleRegistration.java]: @blcham

I have extended the `@Parameter` annotation by adding the handler field.

The documentation has also been updated as well.

File: s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java (hunk 3 above)
Comment (palagdan) [reply s-pipes-modules/module-tabular/src/main/java/cz/cvut/spipes/modules/TabularModule.java]: It was replaced by handler field in an annotation.

**Review by blcham — CHANGES_REQUESTED** [review]
LGTM, just resolve the provided comments, after that you can Merge (but watch out -- we want to have merge commit as well)

File: s-pipes-core/src/main/java/cz/cvut/spipes/modules/Parameter.java [hunk 4]
```diff
@@ -1,13 +1,68 @@
...
+ * {@link #iri()} attribute specifies the IRI of the RDF property. The field's value is
+ * set based on the object of the RDF triple with the given property IRI.</p>
+ *
+ * <p>Key attributes:
+ * <ul>
+ *   <li>{@link #iri()} specifies the IRI of the RDF property associated with the field.
+ *       This IRI links the field to a specific property in the RDF data model.</li>
+ *   <li>{@link #comment()} allows an optional description or note about the parameter for documentation or informational purposes.</li>
+ *   <li>{@link #handler()} allows the specification of a custom {@link Handler} implementation
+ *       for managing the field's value. If not provided, the {@link Handler} is used by default.</li>
```
[the remark this answers is not in the document]
Comment (palagdan) [reply s-pipes-core/src/main/java/cz/cvut/spipes/modules/Parameter.java:24]: @blcham 

First, I added a DefaultHandler, which does nothing but serves as the default value for the handler field. Later, I decided to use the Handler class itself instead of creating a separate one just for the default value.

In this setup, if the handler is the default class Handler, we use the handler from the type. Otherwise, we use a custom handler. Essentially, we don’t create an instance of the abstract class; it serves purely as a marker.

[the remark this answers is not in the document]
Comment (blcham) [reply s-pipes-core/src/main/java/cz/cvut/spipes/modules/Parameter.java:23]: Ok, Let's talk about this on next meeting. To me this is very confusing ...

To me DefaultHandler seems to have perfect sense ... it is just delegating work to other Handlers using Registry ... So the strange code of type:
```
     if(handlerClazz != Handler.class){
        ...
             else{
                    HandlerRegistry handlerRegistry = HandlerRegistry.getInstance();
                    Handler<?> typeHandler = handlerRegistry.getHandler(f.getType(), resource, executionContext, setter);
                    typeHandler.setValueByProperty(ResourceFactory.createProperty(p.iri()));
```
would not have to exist, because you would treat it as regular handler without need to do `if ... else`
